//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using BenchmarkDotNet.NUnit;

using NUnit.Framework;

using IntOp = CodeJam.Arithmetic.Operators<int>;
using NullableDoubleOp = CodeJam.Arithmetic.Operators<double?>;

using static CodeJam.AssemblyWideConfig;

namespace CodeJam.Arithmetic
{
	[TestFixture(Category = BenchmarkConstants.BenchmarkCategory + ": Operators (generated)")]
	[CompetitionMetadata("CodeJam.Arithmetic.NumOperatorsPerfTest.generated.xml")]	
	public class NumOperatorsPerfTest
	{
		[Test]
		public void IntUnaryMinus() => CompetitionBenchmarkRunner.Run<IntUnaryMinusCase>(RunConfig);

		public class IntUnaryMinusCase: IntOperatorsBenchmark<int>
		{
			private readonly Func<int, int> _intUnaryMinus = IntOp.UnaryMinus;

			[CompetitionBaseline]
			public void UnaryMinusBaseline()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = -ValuesB[i];
			}

			[CompetitionBenchmark]
			public void UnaryMinusOperator()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = _intUnaryMinus(ValuesB[i]);
			}
		}

		[Test]
		public void IntOnesComplement() => CompetitionBenchmarkRunner.Run<IntOnesComplementCase>(RunConfig);

		public class IntOnesComplementCase: IntOperatorsBenchmark<int>
		{
			private readonly Func<int, int> _intOnesComplement = IntOp.OnesComplement;

			[CompetitionBaseline]
			public void OnesComplementBaseline()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = ~ValuesB[i];
			}

			[CompetitionBenchmark]
			public void OnesComplementOperator()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = _intOnesComplement(ValuesB[i]);
			}
		}

		[Test]
		public void IntPlus() => CompetitionBenchmarkRunner.Run<IntPlusCase>(RunConfig);

		public class IntPlusCase: IntOperatorsBenchmark<int>
		{
			private readonly Func<int, int, int> _intPlus = IntOp.Plus;

			[CompetitionBaseline]
			public void PlusBaseline()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = ValuesA[i] + ValuesB[i];
			}

			[CompetitionBenchmark]
			public void PlusOperator()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = _intPlus(ValuesA[i], ValuesB[i]);
			}
		}

		[Test]
		public void NullableDoublePlus() => CompetitionBenchmarkRunner.Run<NullableDoublePlusCase>(RunConfig);

		public class NullableDoublePlusCase: NullableDoubleOperatorsBenchmark<double?>
		{
			private readonly Func<double?, double?, double?> _doublePlus = NullableDoubleOp.Plus;

			[CompetitionBaseline]
			public void PlusBaseline()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = ValuesA[i] + ValuesB[i];
			}

			[CompetitionBenchmark]
			public void PlusOperator()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = _doublePlus(ValuesA[i], ValuesB[i]);
			}
		}

		[Test]
		public void IntMinus() => CompetitionBenchmarkRunner.Run<IntMinusCase>(RunConfig);

		public class IntMinusCase: IntOperatorsBenchmark<int>
		{
			private readonly Func<int, int, int> _intMinus = IntOp.Minus;

			[CompetitionBaseline]
			public void MinusBaseline()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = ValuesA[i] - ValuesB[i];
			}

			[CompetitionBenchmark]
			public void MinusOperator()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = _intMinus(ValuesA[i], ValuesB[i]);
			}
		}

		[Test]
		public void NullableDoubleMinus() => CompetitionBenchmarkRunner.Run<NullableDoubleMinusCase>(RunConfig);

		public class NullableDoubleMinusCase: NullableDoubleOperatorsBenchmark<double?>
		{
			private readonly Func<double?, double?, double?> _doubleMinus = NullableDoubleOp.Minus;

			[CompetitionBaseline]
			public void MinusBaseline()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = ValuesA[i] - ValuesB[i];
			}

			[CompetitionBenchmark]
			public void MinusOperator()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = _doubleMinus(ValuesA[i], ValuesB[i]);
			}
		}

		[Test]
		public void IntMul() => CompetitionBenchmarkRunner.Run<IntMulCase>(RunConfig);

		public class IntMulCase: IntOperatorsBenchmark<int>
		{
			private readonly Func<int, int, int> _intMul = IntOp.Mul;

			[CompetitionBaseline]
			public void MulBaseline()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = ValuesA[i] * ValuesB[i];
			}

			[CompetitionBenchmark]
			public void MulOperator()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = _intMul(ValuesA[i], ValuesB[i]);
			}
		}

		[Test]
		public void NullableDoubleMul() => CompetitionBenchmarkRunner.Run<NullableDoubleMulCase>(RunConfig);

		public class NullableDoubleMulCase: NullableDoubleOperatorsBenchmark<double?>
		{
			private readonly Func<double?, double?, double?> _doubleMul = NullableDoubleOp.Mul;

			[CompetitionBaseline]
			public void MulBaseline()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = ValuesA[i] * ValuesB[i];
			}

			[CompetitionBenchmark]
			public void MulOperator()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = _doubleMul(ValuesA[i], ValuesB[i]);
			}
		}

		[Test]
		public void IntDiv() => CompetitionBenchmarkRunner.Run<IntDivCase>(RunConfig);

		public class IntDivCase: IntOperatorsBenchmark<int>
		{
			private readonly Func<int, int, int> _intDiv = IntOp.Div;

			[CompetitionBaseline]
			public void DivBaseline()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = ValuesA[i] / ValuesB[i];
			}

			[CompetitionBenchmark]
			public void DivOperator()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = _intDiv(ValuesA[i], ValuesB[i]);
			}
		}

		[Test]
		public void NullableDoubleDiv() => CompetitionBenchmarkRunner.Run<NullableDoubleDivCase>(RunConfig);

		public class NullableDoubleDivCase: NullableDoubleOperatorsBenchmark<double?>
		{
			private readonly Func<double?, double?, double?> _doubleDiv = NullableDoubleOp.Div;

			[CompetitionBaseline]
			public void DivBaseline()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = ValuesA[i] / ValuesB[i];
			}

			[CompetitionBenchmark]
			public void DivOperator()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = _doubleDiv(ValuesA[i], ValuesB[i]);
			}
		}

		[Test]
		public void IntModulo() => CompetitionBenchmarkRunner.Run<IntModuloCase>(RunConfig);

		public class IntModuloCase: IntOperatorsBenchmark<int>
		{
			private readonly Func<int, int, int> _intModulo = IntOp.Modulo;

			[CompetitionBaseline]
			public void ModuloBaseline()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = ValuesA[i] % ValuesB[i];
			}

			[CompetitionBenchmark]
			public void ModuloOperator()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = _intModulo(ValuesA[i], ValuesB[i]);
			}
		}

		[Test]
		public void IntXor() => CompetitionBenchmarkRunner.Run<IntXorCase>(RunConfig);

		public class IntXorCase: IntOperatorsBenchmark<int>
		{
			private readonly Func<int, int, int> _intXor = IntOp.Xor;

			[CompetitionBaseline]
			public void XorBaseline()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = ValuesA[i] ^ ValuesB[i];
			}

			[CompetitionBenchmark]
			public void XorOperator()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = _intXor(ValuesA[i], ValuesB[i]);
			}
		}

		[Test]
		public void IntBitwiseAnd() => CompetitionBenchmarkRunner.Run<IntBitwiseAndCase>(RunConfig);

		public class IntBitwiseAndCase: IntOperatorsBenchmark<int>
		{
			private readonly Func<int, int, int> _intBitwiseAnd = IntOp.BitwiseAnd;

			[CompetitionBaseline]
			public void BitwiseAndBaseline()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = ValuesA[i] & ValuesB[i];
			}

			[CompetitionBenchmark]
			public void BitwiseAndOperator()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = _intBitwiseAnd(ValuesA[i], ValuesB[i]);
			}
		}

		[Test]
		public void IntBitwiseOr() => CompetitionBenchmarkRunner.Run<IntBitwiseOrCase>(RunConfig);

		public class IntBitwiseOrCase: IntOperatorsBenchmark<int>
		{
			private readonly Func<int, int, int> _intBitwiseOr = IntOp.BitwiseOr;

			[CompetitionBaseline]
			public void BitwiseOrBaseline()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = ValuesA[i] | ValuesB[i];
			}

			[CompetitionBenchmark]
			public void BitwiseOrOperator()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = _intBitwiseOr(ValuesA[i], ValuesB[i]);
			}
		}

		[Test]
		public void IntLeftShift() => CompetitionBenchmarkRunner.Run<IntLeftShiftCase>(RunConfig);

		public class IntLeftShiftCase: IntOperatorsBenchmark<int>
		{
			private readonly Func<int, int, int> _intLeftShift = IntOp.LeftShift;

			[CompetitionBaseline]
			public void LeftShiftBaseline()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = ValuesA[i] << ValuesB[i];
			}

			[CompetitionBenchmark]
			public void LeftShiftOperator()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = _intLeftShift(ValuesA[i], ValuesB[i]);
			}
		}

		[Test]
		public void IntRightShift() => CompetitionBenchmarkRunner.Run<IntRightShiftCase>(RunConfig);

		public class IntRightShiftCase: IntOperatorsBenchmark<int>
		{
			private readonly Func<int, int, int> _intRightShift = IntOp.RightShift;

			[CompetitionBaseline]
			public void RightShiftBaseline()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = ValuesA[i] >> ValuesB[i];
			}

			[CompetitionBenchmark]
			public void RightShiftOperator()
			{
				for (var i = 0; i < ValuesA.Length; i++)
					Storage = _intRightShift(ValuesA[i], ValuesB[i]);
			}
		}

	}
}